- name: play-01
  hosts: web  # Which hosts your ansible want to connect
  tasks:      # List of task, modules, connections
  - name: play-01 task-01
    ansible.builtin.debug:
      msg: this is from play-01 and task-01