- name: nginx install and run # playbook name
  hosts: web  # Which hosts your ansible want to connect
  become: yes # take sudo access
  tasks:      # List of task, modules, connections
  - name: install nginx #task name
     ansible.builtin.package: # heterogeneous module that can work for all distributions
      name: nginx
      state: present

