- name: variable to print
  hosts: web
  vars: # variable
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{ course }}, duration is: {{ duration }}, trainer: {{ trainer }}"
