- name: variable to print
  hosts: web
  vars: # variable
    course: "Devops with aws from play level" # variable values
    duration: "120hrs"
    trainer: "siva kumar"
  vars_prompt: # prompts the values
  - name: course
    prompt: please enter the course name
    private: false #  not confidential
  tasks:
  - name: print the information
    vars: 
      course: "Devops with aws from task level" # variable values
      duration: "120hrs"
      trainer: "siva kumar"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{ course }}"
  
  
