- name: devops course information
  hosts: local    # to run in ansible server
  vars:
    course: "DevOps with AWS"   # String
    duration: 120   # Integer/Number
    topics:   # Lists
    - Linux
    - Shell
    - Ansible
    - Terraform
    - AWS
    - K8s
    live: true    # Boolean
    tools:    # map/dictionary
      ci: Jenkins   # string
      cm: Ansible
      cloud: AWS
      aws:    # Lists
      - IAM
      - servers
      - S3
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, I am Learning {{ course }}, with duration: {{ duration }}, topics are: {{ topics }}, and live: {{ live }}, tools are: {{ tools }}"

