- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: print the stats
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: install nginx if redhat
    anisible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "Redhat"

  - name: install nginx if debian
    anisible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "debian"    


