- name: loops
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"    # Need to mention item for loops
      state: present   
    loop:   #loop 
    - mysql
    - nginx
    - postfix
    - httpd    