- name: loops
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"    # Need to mention item for loops
      state: "{{ item.state }}"   
    loop:   #loop 
    - { name: 'mysql', state: 'present' }
    - { name: 'nginx', state: 'absent' }
    - { name: 'postfix', state: 'absent' }
    - { name: 'httpd', state: 'present' }    